//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso_Dep
    {
        public string departamento { get; set; }
        public string curso { get; set; }
    
        public virtual Curso Curso1 { get; set; }
        public virtual Departamento Departamento1 { get; set; }
    }
}
