//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaFinal
    {
        public int aluno { get; set; }
        public Nullable<int> ano { get; set; }
        public string curso { get; set; }
        public double notaMed { get; set; }
    
        public virtual Aluno Aluno1 { get; set; }
        public virtual Curso Curso1 { get; set; }
    }
}
